apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: batchjob
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Viresh1994/k8s-deployment-gitops.git
    targetRevision: master
    path: helm-charts/batchjob
    helm:
      valueFiles:
        - helm_charts/batchjob/values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false